### ISSUE TITLE
Adding .env.example

### ISSUE THREAD

**Issue by Debajyoti111** [Aryan-kumar-mains/iNotebook-MernProject#6]
@Aryan-kumar-mains I see that you don't have any `.env.example` file in the project which usually contains the name of environment variables that your project has and instead you have written the environment variables name in `README.md`. `.env.example` file helps contributors in understanding what environment variables your project has and makes it easy for them to contribute. This is also considered best practice.
I can add it to the project if you want, please assign me this issue, a PR will be coming shortly.

**Comment by Aryan-kumar-mains** [comment]
okay @Debajyoti111 go ahead.
